# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- develop
- staging

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  displayName: 'prepare package'
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/s/dist/indive-web/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Indive.WebApp.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  displayName: 'publish artifacts'
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifactType: 'pipeline'
    artifactName: 'package'